name: 15 - Working with Matrices

on: workflow_dispatch

jobs:
  backwards-compatibility:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        node:
          - 18.x
          - 20.x
          - 21.x
        system:
          - ubuntu-latest
          - windows-latest
        include:
          - node: 16.x
            system: ubuntu-latest
          - node: 21.x
            system: ubuntu-latest
            tag: experimental
      fail-fast: true
    name: ${{ matrix.system }}-${{ matrix.node }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Perform some tests
        run: |
          echo "Running tests on OS ${{ matrix.system }} and NodeJS ${{ matrix.node }}"
      - name: Upload test results
        run: echo "Uploading test results"
  include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]
        include:
          - color: red
            opacity: 75
          - shape: circle
            opacity: 100
          - color: red
            shape: triangle
          - opacity: 50
          - color: green
            shape: circle
            size: medium
        exclude:
          - color: green
            shape: circle
    steps:
      - name: Dummy step
        run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
